Spaced out dlc
nsk4762jp/OxygenNotIncluded-Japanese pull request #125
Opened 2021-02-23 10:12 UTC by kankoromochi

「crew」を「乗員→乗組員」、Planetoid, Asteroidを「惑星」→「小惑星」に用語統一、その他誤訳や表現を自然な日本語になるよう微修正。
新しいところは一部翻訳の用語統一が必要なところがあるかもしれませんが、よろしくお願いします。

2021-02-24 02:10 UTC, nsk4762jp requested changes
ざっくりですがレビューしましたので確認をお願いします。

2021-02-24 02:10 UTC, nsk4762jp commented on po/ui.po
> -msgstr "乗員に不備あり"
チェックリストのエラー項目は前に「～に不備あり」でまとめてしまったので、「～警告」と訳す場合は類似箇所の見直しもお願いします。

2021-02-24 02:10 UTC, nsk4762jp commented on po/ui.po
> +msgstr "発射シーケンス開始（デバッグモード）"
全角カッコは翻訳で使っていないので、半角カッコでお願いします。

2021-02-24 02:10 UTC, nsk4762jp commented on po/ui.po
> +msgstr "離陸！"
lift off は「発進」という意味もあるそうです。

[liftoff](https://ejje.weblio.jp/content/liftoff)

2021-02-24 02:10 UTC, nsk4762jp commented on po/ui.po
> +msgstr "コントロールステーションにパイロットが必要です..."
BUILDINGS カテゴリに `Rocket Control Station` という単語がありまして、そこでは `ロケット制御端末` と翻訳しています。  
なので、ここも `制御端末にパイロットが必要です...` になるかと思います。

2021-02-24 02:10 UTC, nsk4762jp commented on po/worlds.po
> +"<smallcaps>水の小惑星は様々な液体や黒鉛の供給源です。地表の島にはさほど多くの"
`Graphite` は今回 `グラファイト` と直訳しています。

2021-02-24 12:35 UTC, kankoromochi commented on po/ui.po
> +"偵察とファーストコンタクトのため、まず最初に<link=\"PIONEERMODULE\">開拓者モ"
承知しました

2021-02-24 12:36 UTC, kankoromochi commented on po/ui.po
> +msgstr "不滅のスーツ"
確かに、無限の方が分かりやすいですね。
訳語については、全体的にひょうきんな感じなので、ちょっとふざけた感じがいいかと思いまして、とりあえず不滅としています。

2021-02-24 12:37 UTC, kankoromochi commented on po/ui.po
> +msgstr "NO EARTHLY RESIN UPDATE"
なるほど。アップデートの固有名詞なのでとりあえずよいかと思います。

2021-02-24 12:38 UTC, kankoromochi commented on po/ui.po
>  #, fuzzy
あ、そうではなく、poeditを使用しておりますので、poeditでこのコメントが残っていたところに関するコメントです。
日本語ＭＯＤのバージョン情報みたいなものが書いてあったのですが、原文は空欄だったので消すべきかどうかわからず…とりあえずコメントは消しておきます。

2021-02-24 12:38 UTC, kankoromochi commented on po/ui.po
> +# 有効な、などの方がよいか？
承知しました。

2021-02-24 12:39 UTC, kankoromochi commented on po/ui.po
> +msgstr "モジュール数制限"
なるほど、その方がよさそうですね。

2021-02-24 12:40 UTC, kankoromochi commented on po/ui.po
> -msgstr "乗員に不備あり"
確かにユレがありますね。日本語の自然さとトレードオフになるところがあるので難しいところですが、一旦不備ありで整えてみます。思いつかなければそのままとしますので適宜修正ください。

2021-02-24 12:40 UTC, kankoromochi commented on po/ui.po
> +msgstr "発射シーケンス開始（デバッグモード）"
失礼しました。

2021-02-24 12:41 UTC, kankoromochi commented on po/ui.po
> +msgstr "離陸！"
宇宙船ですし発進の方が勢いがあっていいかもしれませんね。発進時のメッセージのようですし。

2021-02-24 12:41 UTC, kankoromochi commented on po/ui.po
> +msgstr "コントロールステーションにパイロットが必要です..."
承知しました。

2021-02-24 12:41 UTC, kankoromochi commented on po/worlds.po
> +"<smallcaps>水の小惑星は様々な液体や黒鉛の供給源です。地表の島にはさほど多くの"
気になっていたポイントです　承知しました

2021-02-24 12:58 UTC, kankoromochi commented on po/ui.po
> -msgstr "乗員に不備あり"
考えてみましたが、この場合ですと　乗員に不備あり　とすると、必要な乗員がいない警告なのか、余分な乗員がいる警告なのかがわからなくなってしまいますので、やはり少し表現が難しいです。元の文章と少し離れてしまいますが、意味が取りやすいように「警告:〇〇確認」を基本に文章的に表現してみます。

2021-02-24 13:00 UTC, kankoromochi commented on po/ui.po
> +msgstr "離陸！"
take off もまとめて、発進に表現をまとめました。（お堅く用語を使うなら離昇かもしれませんが、雰囲気にはあいませんかね）

2021-02-24 14:27 UTC, nsk4762jp commented on po/ui.po
>  #, fuzzy
あー、「原文が空のときにMODバージョン情報が出るやつ」は *.pot を取り込むとたまにある現象です。
ごっそり削除してもらって構いません。

2021-02-25 23:58 UTC, nsk4762jp approved these changes

2021-02-25 23:59 UTC, merged