equipmentまで下から翻訳
nsk4762jp/OxygenNotIncluded-Japanese pull request #128
Opened 2021-03-13 14:02 UTC by kankoromochi

部分的ですがご確認お願いします。（特に翻訳ユレ

2021-03-13 14:17 UTC, kankoromochi commented
コメントした通り、equipment以降（以上？）特に変更ないのでこれでcluster_names以降の変更すべて終了したかと存じます。

2021-03-13 23:18 UTC, nsk4762jp commented
どうもありがとうございます！
これから確認します。

2021-03-14 07:14 UTC, nsk4762jp requested changes
ざっくりとですが確認しました。
修正が必要そうなところはコメントしてありますのでよろしくお願いします。

2021-03-14 13:59 UTC, kankoromochi commented on po/equipment.po
> +msgstr "お持ち帰り用の肺、といったところです。"
すみません、誤訳です。　日本語のわかりやすさを重視してみます。

2021-03-14 13:59 UTC, kankoromochi commented on po/equipment.po
> +"スーツは<link=\"CRAFTINGTABLE\">作業端末</link>修理できます。"
表記統一のためにコピペしたのが原因です。修正します

2021-03-14 14:00 UTC, kankoromochi commented on po/misc.po
> +"from getting <link=\"RADIATIONSICKNESS\">Radiation Sickness</link> ."
確認します。

2021-03-14 14:00 UTC, kankoromochi commented on po/misc.po
> +msgstr "原子炉メルトダウン"
承知しました。反応炉に統一します。

2021-03-14 14:01 UTC, kankoromochi commented on po/misc.po
> +"A Research Reactor has overheated and is meltingdown! Extreme radiation is "
ResearchReactor周りの訳語についてまよっていましたので、それで統一します。

2021-03-14 14:01 UTC, kankoromochi commented on po/misc.po
> +"アイテムは装備するたびに耐久度が失われ、耐久度が0％に達すると複製人間は着用で"
承知しました。

2021-03-14 14:04 UTC, kankoromochi commented on po/ui.po
> +msgstr "全てが\"RAD\"になります。 {Hotkey}"
これは多分放射、放射能とともにおっしゃる通りイカしたの口語、あとはradical由来の過激な、ヤバイみたいな意味合いをひっかけていると解釈しました。
radの多義性にかかわるので正直かなり難しいですね。もうあきらめて直訳にしたので、とりあえずいい翻訳が提案されるまで保留しておきたいと思います。

2021-03-14 14:36 UTC, kankoromochi commented on po/items.po
> +"<link=\"HIGHENERGYPARTICLEREDIRECTOR\">ラッドボルト反射器</link>で大部分を反"
承知しました

2021-03-16 10:21 UTC, nsk4762jp approved these changes
OKです。

2021-03-16 10:22 UTC, nsk4762jp commented
確認できたので、これで取り込もうと思います。
どうもありがとうございました！

2021-03-16 10:22 UTC, merged