DLC仕様のロケットに関する翻訳について
nsk4762jp/OxygenNotIncluded-Japanese pull request #136
Opened 2021-06-27 10:52 UTC by denev-rove

ご無沙汰しています。

先日、なんの事前知識もないまま Spaced Out! を遊んでいたのですが、ロケットの仕様を理解するまでに苦労したので、その経験を活かして、新仕様のロケット周りの翻訳を見直してみました。
なるべく実際の仕様を誤解なく読み取れることを至上命題にしたため、少し超訳っぽい部分もあります。

ついでに、あるいてど文言の統一も行ったため、予想外に変更範囲が広くなってしまいました。

まだ Spaced Out! 自体が開発中であるためか、原文自体に表記ゆれや仕様と合わない説明があるようです。
（ロケットの全長とモジュール数の混同など）
そのあたりは全てそのまま訳しています。

以上、翻訳活動の足しになれば幸いです。

2021-07-01 12:39 UTC, nsk4762jp requested changes
ざっくりとですが確認しました。  
コメントが付いてない箇所はOKまたは類似見直しの対象になります。
よろしくお願いします。

2021-07-01 16:52 UTC, denev-rove commented on po/ui.po
> +msgstr "目的地を設定するには、ロケットの制御モジュールを選択してください"
実際の仕様に合わせています。basic noseconeには制御モジュールとしての機能がないため、目的地の設定ができません。逆に，Spacefarer Moduleは制御モジュールとしての機能を持つため、目的地の設定ができます。原文は、古い仕様のままなのかもしれません。

2021-07-01 16:58 UTC, denev-rove commented on po/ui.po
> +msgstr "採掘中…"
了解しました。

2021-07-01 17:04 UTC, denev-rove commented on po/buildings.po
> +"制御カプセルはロケットの先端に取り付けなければなりません。"
当初は「最上部」と訳したのですが、既存の訳に「先端」としているものが幾つかあったので、そちらに合わせました。bottomの訳が「最後尾」となっていたので、対義語としても「先端」のほうがそれっぽい気がします。

2021-07-01 17:15 UTC, denev-rove commented on po/building.po
> +msgstr "{Destination_Asteroid}へ航行中: {ETA}"
似たような表記ゆれとして、`launch`も悩みました。ロケットの場合`発射`よりも`打ち上げ`とするのが雰囲気が出ると思うのですが、今回は語感を優先して`発射`や`発進`のままとしている箇所があります。原文でも`take off`など表記ゆれがあるので、個人的には、無理に統一しなくてもいいかなと思っています。

2021-07-02 09:45 UTC, denev-rove commented on po/building.po
> +"ジュール</link>の下に建造しなければなりません"
了解しました。
既存の訳で`建造`としていた部分があったので試しに差別化してみましたが、今後は`建設`で統一させていただきます。気付いた範囲で既存の訳も修正したいと思います。

余談ですが、似たような単語として`install`の訳にも悩みました。ひとまず「取り付ける」で（一部を除いて）統一しましたが、モジュールを積み重ねて組み立てるというロケットの構造上、いまいちしっくりきていません。が、ほかにいい表現も思い浮かばないので妥協しています。

2021-07-02 09:51 UTC, denev-rove commented on po/buildings.po
> +msgstr "固形酸化剤は真空の宇宙空間で効率よく燃料を燃焼させることができます。"
とても細かいこだわりなのですが、酸化剤と燃料は別物である（あくまで「燃」えるのは燃料であって、酸化剤は物が燃える（つまり、酸化する）のに必要な物質である）という位置づけです。

2021-07-02 09:56 UTC, denev-rove commented on po/ui.po
> +msgstr "貨物の搬出は全て完了しています"
STRINGS.UI.STARMAP.LAUNCHCHECKLIST.CARGO_TRANSFER_COMPLETE.TOOLTIP.READY
STRINGS.UI.STARMAP.LAUNCHCHECKLIST.LOADING_COMPLETE.TOOLTIP.READY

上記ふたつの文言が全く同じものになっていたので、実際の仕様に合わせて差別化したのですが…。
LOADING_COMPLETEのほうはともかく、CARGO_TRANSFER_COMPLETEのほうは仕様を正しく把握しきれていませんでしたので、ひとまず原文どおり`搬入出`にしたいと思います。

今後、仕様を詳細に把握しましたら、また提案させていただくかもしれません。

2021-07-02 09:58 UTC, denev-rove commented on po/ui.po
> +msgstr "ロケットの全長が着陸地点の広さに対して長すぎます"
ここは表現に悩んだところでした。
とても自然で正確な表現になっていると思いますので、`着陸地点の空間に対して長すぎます`にさせていただきます。

2021-07-02 09:59 UTC, denev-rove commented on po/ui.po
> +msgstr "全ての複製人間がモジュール内部へ自由に出入りできます"
同感ですので、そのようにさせていただきます。

2021-07-02 11:56 UTC, denev-rove commented on po/buildings.po
> +msgstr ""
ここは主に、現行訳で省略されている`conveniently`の語意を補足する意図で修正しています。（ついでに「複製人間によるコメント」という体で語尾を口語調にしています。）

2021-07-02 12:14 UTC, nsk4762jp commented
8b311b0 修正分について確認しました。特に指摘はありません。

2021-07-02 14:18 UTC, denev-rove commented
レビューありがとうございました。
競合の解消のやり方が分からずに手間取ってしまいました。これでマージできる状態になっているでしょうか。
よろしくお願いします。

2021-07-02 14:59 UTC, nsk4762jp commented
どうもありがとうございます。上手くマージできそうなのでこれで取り込みます。

2021-07-02 14:59 UTC, merged